import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Feeds from "../components/Feeds";
import Form from "../components/Form";
import { fetchFeed } from "../utils/apiCalls";
import { useGlobalContext } from "../lib/context";
import Navbar from "../components/Navbar";

export default function Home({ data }) {
  const { getFeeds } = useGlobalContext();

  const [currentId, setCurrentId] = useState(null);

  //update the state
  useEffect(() => {
    if (data) {
      getFeeds(data);
    }
  }, []);

  //scrolling using forwardRef
  const formRef = useRef();
  const editingOnClick = () => {
    formRef.current.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className="bg-black flex flex-col justify-center items-center ">
      <Head>
        <title>MicroBlog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-3 max-w-screen-sm w-full text-gray-200 font-display md:max-w-2xl md:w-full">
        <Navbar />
        <div className="w-full">
          <Form
            currentId={currentId}
            setCurrentId={setCurrentId}
            ref={formRef}
          />
          <Feeds setCurrentId={setCurrentId} editingOnClick={editingOnClick} />
        </div>
      </main>
    </div>
  );
}

//fetching the data
export const getStaticProps = async () => {
  const { data } = await fetchFeed();

  return { props: { data } };
};
